apiVersion: apps/v1
kind: Deployment
metadata:
  name: depfrontendwebapp
  labels:
    app: frontendwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontendwebapp
  template:
    metadata:
      labels:
        app: frontendwebapp
    spec:
      containers:
      - name: frontendwebapp
        image: ArgoCD-Tutorial-Image:main
        ports:
        - containerPort: 80
