apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-webapp-development
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webapp=tacksam/dummy-webapp:dev  #Change to the production image that you pushed before
    argocd-image-updater.argoproj.io/update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/SMaltin93/tutorial-ArgoCd-multi-branch-pipeline  #Change to your repository
    targetRevision: dev
    path: manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-webapp-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
