 apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: multi-branch-pipeline-main
     namespace: argocd
   spec:
     project: default
     source:
       repoURL: https://github.com/SMaltin93/tutorial-ArgoCd-multi-branch-pipeline 
       targetRevisio/n: main
       path: manifests/
     destination:
       server: https://kubernetes.default.svc
       namespace: default
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
